title: Aman Bhojak
logo: "/asset/aman.jpg"
description: >
  <br>
  **Fresh Graduate | Continous Learner**
  <br>
  <a href="https://www.linkedin.com/in/aman-bhojak-21150321a/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:realaman09@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>

theme: jekyll-theme-minimal