title: Aman Bhojak
logo: "/asset/aman.jpg"
description: >
  <br>
  <b>Fresh Graduate | Continous Learner</b>
  <br>
  <a href="https://github.com/aman-bhojak?tab=repositories">
    <img src="https://img.shields.io/badge/github%20-%23121011.svg?&style=for-the-badge&logo=github&logoColor=white">
  </a>
  <a href="mailto:realaman09@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
  <a href="https://wa.me/8094377204">
    <img alt="Gmail" src="https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white" />
  </a>

theme: jekyll-theme-minimal